server {
    listen 80;

    location = / {
        return 301 /anxiety_tips/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /anxiety_tips/index.html;
    }

    error_page 404 /anxiety_tips/index.html;

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
